DROP TRIGGER IF EXISTS session_rsvps_notify ON session_rsvps;
DROP TRIGGER IF EXISTS notifications_notify ON notifications;
DROP TRIGGER IF EXISTS rfid_tags_notify ON rfid_tags;
DROP TRIGGER IF EXISTS team_member_sessions_notify ON team_member_sessions;
DROP TRIGGER IF EXISTS team_members_notify ON team_members;
DROP TRIGGER IF EXISTS locations_notify ON locations;
DROP TRIGGER IF EXISTS sessions_notify ON sessions;
DROP FUNCTION IF EXISTS notify_table_change();
DROP VIEW IF EXISTS user_permissions;
DROP VIEW IF EXISTS permissions_effective;
DROP TABLE IF EXISTS role_permissions;
DROP TYPE IF EXISTS permission_level;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS session_rsvp_messages;
DROP TABLE IF EXISTS session_rsvps;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS team_member_sessions;
DROP TABLE IF EXISTS rfid_tags;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS logos;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS secrets;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS users;
